; This file is used to specify the default values for editor settings
; These are set for new users but individuals can override that in the editor settings UI

[/Script/UnrealEd.LevelEditorPlaySettings]
GameGetsMouseControl=True
RouteGamepadToSecondWindow=True
NetworkEmulationSettings=(bIsNetworkEmulationEnabled=True,EmulationTarget=Server,CurrentProfile="Average",OutPackets=(MinLatency=30,MaxLatency=60,PacketLossPercentage=1),InPackets=(MinLatency=30,MaxLatency=60,PacketLossPercentage=1))

; Enable the plugins and favorites to be displayed by default
[/Script/UnrealEd.ContentBrowserSettings]
DisplayPluginFolders=True
DisplayFavorites=True

[ContentBrowser]
FavoritePaths=/Warfare_Demonstration_Land,/Warfare_Assets,/Core_Collection,/Elemental_Collection,/GameFeatures
; Make all the content browsers have the Favorites expanded too
ContentBrowserTab1.FavoritesAreaExpanded=True
ContentBrowserTab2.FavoritesAreaExpanded=True
ContentBrowserTab3.FavoritesAreaExpanded=True
ContentBrowserTab4.FavoritesAreaExpanded=True
ContentBrowserDrawer.FavoritesAreaExpanded=True


; Some commonly used editor maps that will be displayed in the editor task bar
; Legacy Lyra developer settings removed from the UGE target defaults.
;[/Script/LyraGame.LyraDeveloperSettings]
;+CommonEditorMaps=/Warfare_Demonstration_Land/Maps/Demonstration.Demonstration

[/Script/LogLevelEditor.LogLevelEditor_Settings]
bAlsoScanModuleLogCategories=True

