// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace GameplayTags_Core
{
	CORE_STRUCTURE_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Core will use
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	CORE_STRUCTURE_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	CORE_STRUCTURE_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	CORE_STRUCTURE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_MovementStopped);
}
